Merged revisions 32369,32410-32412,32414-32417,32419-32423,32426-32430,32433-32441,32445-32448,32452-32453,32455,32457,32459-32461,32463,32466,32470-32475,32477,32479-32482,32484 via svnmerge from https://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk
........
  r32369 | mgist | 2009-05-09 23:24:19 +0200 (Sat, 09 May 2009) | 1 line
  
  - Fixed missing return.
........
  r32410 | res2002 | 2009-05-22 14:26:00 +0200 (Fri, 22 May 2009) | 1 line
  
  Change material specular settings to make level look like original castle
........
  r32411 | res2002 | 2009-05-22 14:57:30 +0200 (Fri, 22 May 2009) | 1 line
  
  Add texture class for height maps
........
  r32412 | res2002 | 2009-05-22 14:59:12 +0200 (Fri, 22 May 2009) | 1 line
  
  Add coercion for direction_object to direction_world
........
  r32414 | res2002 | 2009-05-22 19:47:25 +0200 (Fri, 22 May 2009) | 1 line
  
  Add serialization methods for bit arrays
........
  r32415 | res2002 | 2009-05-22 19:49:01 +0200 (Fri, 22 May 2009) | 1 line
  
  Include CS version number in user shader cache path (to avoid future clashes between versions)
........
  r32416 | res2002 | 2009-05-22 19:53:50 +0200 (Fri, 22 May 2009) | 3 lines
  
  Instead of caching techniques for each "tech variation", cache techniques only
  once, and store with techniques are used by a "tech variation".
........
  r32417 | mgist | 2009-05-22 21:11:24 +0200 (Fri, 22 May 2009) | 2 lines
  
  - Made csProcTexture hold a ref to the texture it creates.
  - Small cleanup.
........
  r32419 | crystal-manage | 2009-05-23 05:12:35 +0200 (Sat, 23 May 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32420 | mgist | 2009-05-23 12:43:56 +0200 (Sat, 23 May 2009) | 1 line
  
  - Made BlockAlloc in SliceAllocator thread safe.
........
  r32421 | mgist | 2009-05-24 21:14:58 +0200 (Sun, 24 May 2009) | 1 line
  
  - Add fallback to parallax occlusion snippet.
........
  r32422 | mgist | 2009-05-25 14:42:28 +0200 (Mon, 25 May 2009) | 1 line
  
  - Added weaver terrain splat shader.
........
  r32423 | mgist | 2009-05-25 15:08:55 +0200 (Mon, 25 May 2009) | 4 lines
  
  - Terrainf changes;
  * Changed to use the weaver terrain splat shader.
  * Added a normalmap to the path.
  * Fixed the radius on some meshgen geometry.
........
  r32426 | mgist | 2009-06-03 04:07:52 +0200 (Wed, 03 Jun 2009) | 1 line
  
  - Added nodecal option to mesh params.
........
  r32427 | mgist | 2009-06-03 19:40:14 +0200 (Wed, 03 Jun 2009) | 1 line
  
  - Added control of normal map tiling to water_plane shader.
........
  r32428 | res2002 | 2009-06-04 01:52:09 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Use true orthographic camera for isotest
........
  r32429 | mgist | 2009-06-04 01:56:57 +0200 (Thu, 04 Jun 2009) | 1 line
  
  - Fixed ocean mesh vertex setup.
........
  r32430 | res2002 | 2009-06-04 03:01:46 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  Do not manually define _SCL_SECURE to 0 as this introduced a non-obvious incompatibility when STL is used with external libraries
  as the default value for _SCL_SECURE is 1 and the different values affect the memory layout of STL classes.
  Probably fixes #661.
........
  r32433 | res2002 | 2009-06-04 13:00:23 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Get rid of specific shaders, renderloop remnants, lightmaps
........
  r32434 | res2002 | 2009-06-04 14:18:16 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Prevent an SV binary compatibility issue between debug and optimize builds.
........
  r32435 | res2002 | 2009-06-04 14:24:09 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Don't hit config manager every frame to query max portal recurse count
........
  r32436 | res2002 | 2009-06-04 14:32:40 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Also emit string markers in optimize builds (they're useful & cheap enough)
........
  r32437 | res2002 | 2009-06-04 16:28:08 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  Some DrawSimpleMesh enhancements:
  - Ability to specify index ranges like in rendermesh
  - Method for bulk-drawing multiple simplemeshes
........
  r32438 | res2002 | 2009-06-04 16:28:36 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Improve CEGUI drawing
........
  r32439 | res2002 | 2009-06-04 17:00:37 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Implement DrawSimpleMeshes()
........
  r32440 | res2002 | 2009-06-04 21:59:36 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Reduced csShaderVariable memory footprint
........
  r32441 | res2002 | 2009-06-04 22:42:20 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Add iView::GetCustomMatrixCamera()
........
  r32445 | sunshine | 2009-06-04 23:10:07 +0200 (Thu, 04 Jun 2009) | 2 lines
  
  Fixed compilation error: operands of ?: have different types
........
  r32446 | sunshine | 2009-06-04 23:20:06 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  'weltall' improved csCommandLineParser::GetName() documentation.
  From #663.
........
  r32447 | sunshine | 2009-06-04 23:22:36 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  'weltall' added multi-file processing capability to 'docconv'.
  Closes #663.
........
  r32448 | res2002 | 2009-06-04 23:30:46 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Copy comment improvement from r32446 to public interface.
........
  r32452 | res2002 | 2009-06-05 01:30:05 +0200 (Fri, 05 Jun 2009) | 1 line
  
  Update for new cs-win32libs
........
  r32453 | crystal-manage | 2009-06-05 05:17:55 +0200 (Fri, 05 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32455 | res2002 | 2009-06-05 13:53:32 +0200 (Fri, 05 Jun 2009) | 1 line
  
  Remove wxtypical MSVC workspace - WX is now shipped with cs-win32libs, so the app+plugin using it can be in the 'typical' workspace as well
........
  r32457 | crystal-manage | 2009-06-05 14:45:29 +0200 (Fri, 05 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32459 | res2002 | 2009-06-07 20:23:02 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Don't link external libraries from _all_ plugins into static plugin library users
........
  r32460 | res2002 | 2009-06-07 20:27:55 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Clean up plugins excluded from MSVC static plugins lib
........
  r32461 | res2002 | 2009-06-07 20:58:47 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Correctly deal with platforms in per-file configurations
........
  r32463 | crystal-manage | 2009-06-08 05:16:58 +0200 (Mon, 08 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32466 | res2002 | 2009-06-09 00:48:01 +0200 (Tue, 09 Jun 2009) | 1 line
  
  Fixed precaching for shaders w/o variations in techs
........
  r32470 | sunshine | 2009-06-10 10:00:54 +0200 (Wed, 10 Jun 2009) | 10 lines
  
  Fixed r32206 problem (and indirectly r29796 due to illogical and
  unexpected code placement) where configure.ac attempted (and failed) to
  emit -mmmx, -msse, -msse2, and -mfpmath=sse CFLAGS to Jamconfig before
  checking if the compiler recognized those flags.
  
  Also reversed r29796 policy of checking for these flags on every platform
  but only utilizing them on Mac OS X. Instead, now utilizes them, if
  recognized, regardless of platform. (It is not clear why the r29796 policy
  was chosen.)
........
  r32471 | sunshine | 2009-06-10 10:01:21 +0200 (Wed, 10 Jun 2009) | 2 lines
  
  Regenerated configure following r32470.
........
  r32472 | res2002 | 2009-06-11 16:02:24 +0200 (Thu, 11 Jun 2009) | 1 line
  
  Explicitly use LoadLibraryA in CacheDLL class
........
  r32473 | res2002 | 2009-06-15 12:46:05 +0200 (Mon, 15 Jun 2009) | 1 line
  
  Remove a deprecated method
........
  r32474 | res2002 | 2009-06-15 16:49:24 +0200 (Mon, 15 Jun 2009) | 1 line
  
  Merge hacky iGenMeshAnimationControl1_4 into iGenMeshAnimationControl
........
  r32475 | res2002 | 2009-06-15 16:52:03 +0200 (Mon, 15 Jun 2009) | 1 line
  
  Use a bit tighter includes for bindings glue
........
  r32477 | res2002 | 2009-06-15 20:14:33 +0200 (Mon, 15 Jun 2009) | 1 line
  
  Check anim_ctrl for not being 0 before using it
........
  r32479 | crystal-manage | 2009-06-16 05:15:06 +0200 (Tue, 16 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32480 | res2002 | 2009-06-17 16:17:14 +0200 (Wed, 17 Jun 2009) | 1 line
  
  Fix csInitializer::CreateEnvironment() for Python (was broken after addition of optional bool argument)
........
  r32481 | res2002 | 2009-06-17 16:25:28 +0200 (Wed, 17 Jun 2009) | 1 line
  
  Fix for iImageIO move
........
  r32482 | res2002 | 2009-06-17 16:51:00 +0200 (Wed, 17 Jun 2009) | 1 line
  
  Remove leftover CS_REQUEST_IMAGELOADER
........
  r32484 | crystal-manage | 2009-06-18 05:17:08 +0200 (Thu, 18 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/branches/feature/plugin-merge@32487 8cc4aa7f-3514-0410-904f-f2cc9021211c